"""empty message

Revision ID: 13b8e6e78788
Revises: a1f9d30870ad
Create Date: 2019-11-14 23:02:55.758824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b8e6e78788'
down_revision = 'a1f9d30870ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_pessoa', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nr_documento', sa.String(), nullable=True),
    sa.Column('id_endereco', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pessoa')
    # ### end Alembic commands ###
