"""empty message

Revision ID: 6ea18186d29d
Revises: e533095e0770
Create Date: 2019-11-16 18:04:26.065071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea18186d29d'
down_revision = 'e533095e0770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_enum_produto_ingreditente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_enum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=True),
    sa.Column('qtd_produto', sa.Integer(), nullable=True),
    sa.Column('preco_venda_unidade', sa.Float(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tb_enum_produto_ingreditente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_produto')
    op.drop_table('tb_enum_produto_ingreditente')
    # ### end Alembic commands ###
