"""empty message

Revision ID: a1f9d30870ad
Revises: 
Create Date: 2019-11-14 22:46:16.050015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f9d30870ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('tes', sa.NUMERIC(), nullable=True)
    )
    # ### end Alembic commands ###
