"""empty message

Revision ID: e533095e0770
Revises: 13b8e6e78788
Create Date: 2019-11-15 14:23:07.430667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e533095e0770'
down_revision = '13b8e6e78788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_perfil', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_permissao', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permissao_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('id_permissao', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['tb_perfil.id'], ),
    sa.ForeignKeyConstraint(['id_permissao'], ['tb_permissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_permissao_perfil')
    op.drop_table('tb_permissoes')
    op.drop_table('tb_perfil')
    # ### end Alembic commands ###
