"""empty message

Revision ID: f1de3147c347
Revises: 
Create Date: 2019-11-19 11:01:06.191026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1de3147c347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_enum_produto_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_enum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_perfil', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_permissao', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_pessoa', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nr_documento', sa.String(), nullable=True),
    sa.Column('id_endereco', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permissao_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('id_permissao', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['tb_perfil.id'], ),
    sa.ForeignKeyConstraint(['id_permissao'], ['tb_permissoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=True),
    sa.Column('qtd_produto', sa.Integer(), nullable=True),
    sa.Column('preco_venda_unidade', sa.Float(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tb_enum_produto_ingrediente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['tb_perfil.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    op.drop_table('tb_produto')
    op.drop_table('tb_permissao_perfil')
    op.drop_table('tb_pessoa')
    op.drop_table('tb_permissoes')
    op.drop_table('tb_perfil')
    op.drop_table('tb_enum_produto_ingrediente')
    # ### end Alembic commands ###
